/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.db_configuration;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Maudy
 */
public class addPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dolphinList
     */
    public addPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
      Color navcolor = new Color(102,0,51);
     Color headcolor = new Color(102,0,51);
      Color bodycolor = new Color(255,0,165);
      
      ButtonGroup group = new ButtonGroup();
  
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sex = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        ADD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        bdate = new javax.swing.JTextField();
        dhired = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Other = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bsal = new javax.swing.JTextField();
        Female = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADD.setBackground(new java.awt.Color(102, 0, 51));
        ADD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel5.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD EMPLOYEE");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 200, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("___________________________________________________");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 780, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD EMPLOYEE");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 200, 50));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 270, 30));

        bdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 270, 30));

        dhired.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dhired.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(dhired, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 270, 30));

        job.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        job.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });
        jPanel5.add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 270, 30));

        department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel5.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 270, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Department");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Job Title");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date Hired");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Date of Birth");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 30));

        Other.setBackground(new java.awt.Color(0, 204, 153));
        sex.add(Other);
        Other.setText("Other");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Other, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), Other, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        Other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherActionPerformed(evt);
            }
        });
        jPanel5.add(Other, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        Male.setBackground(new java.awt.Color(0, 204, 153));
        sex.add(Male);
        Male.setText("Male");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Male, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), Male, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel5.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Sex");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 50));

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Engage", "Married", "Widow" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        jPanel5.add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 270, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Basic Salary");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 150, 30));

        bsal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(bsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 270, 30));

        Female.setBackground(new java.awt.Color(0, 204, 153));
        sex.add(Female);
        Female.setText("Female");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), Female, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        jPanel5.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 660));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setBackground(bodycolor);
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
        ADD.setBackground(headcolor);
    }//GEN-LAST:event_ADDMouseExited

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
  db_configuration dbc = new db_configuration();
        
  
  dbc.insertData("INSERT INTO tbl_e( "
          + "e_name, e_bdate, e_sex, e_status, e_dep, e_job, e_dhired, e_bsal)VALUES('"
          +name.getText()+"','"
          +bdate.getText()+"','"
          +sex.getSelection().getActionCommand()+"','"
          +combox.getSelectedItem().toString()+"','"
          +department.getText()+"','"
          +job.getText()+"','"
          +dhired.getText()+"','"
          +bsal.getText()+"')"); 
       
        
           name.setText("");
           department.setText("");
           bdate.setText("");
           dhired.setText("");
           bsal.setText("");
           job.setText("");
           sex.clearSelection();
           JOptionPane.showMessageDialog(null, "SUCCESSFULLY ADDED!");
    }//GEN-LAST:event_ADDActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void OtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherActionPerformed
        
    }//GEN-LAST:event_OtherActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
      
    }//GEN-LAST:event_MaleActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    public static javax.swing.JRadioButton Female;
    public static javax.swing.JRadioButton Male;
    public static javax.swing.JRadioButton Other;
    public static javax.swing.JTextField bdate;
    public static javax.swing.JTextField bsal;
    public static javax.swing.JComboBox<String> combox;
    public static javax.swing.JTextField department;
    public static javax.swing.JTextField dhired;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JTextField job;
    public static javax.swing.JTextField name;
    public static javax.swing.ButtonGroup sex;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
