/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import myapp.loginPage;

/**
 *
 * @author Maudy
 */
public class settingPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form settingPage
     */
    public settingPage() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
      Color navcolor = new Color(94,24,59);
     Color headcolor = new Color(3,156,117);
      Color bodycolor = new Color(0,180,140);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        reps = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logOut = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editProf = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel1.setText("ACCOUNT SETTINGS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 270, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("ADDRESS: PANCIL, BARILI, CEBU");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 180, 290, 30);

        jPanel3.setBackground(new java.awt.Color(255, 0, 165));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("Maudy Saylanon");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 160, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-person-female-101.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 190));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(480, 20, 280, 260);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("ACCOUNT: MAUDY ARNIDO SAYLANON");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 270, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("POSITION: ADMINISTRATOR");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 100, 210, 30);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("EMAIL: maudyarnido@gmail.com");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 130, 250, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 830, 300));

        jPanel4.setBackground(new java.awt.Color(3, 167, 125));
        jPanel4.setLayout(null);

        reps.setBackground(new java.awt.Color(3, 156, 117));
        reps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repsMouseExited(evt);
            }
        });
        reps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REPORTS");
        reps.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-reports-100.png"))); // NOI18N
        reps.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel4.add(reps);
        reps.setBounds(310, 70, 200, 180);

        logOut.setBackground(new java.awt.Color(3, 156, 117));
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        logOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOGOUT");
        logOut.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-log-out-100.png"))); // NOI18N
        logOut.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel4.add(logOut);
        logOut.setBounds(580, 70, 200, 180);

        editProf.setBackground(new java.awt.Color(3, 156, 117));
        editProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfMouseExited(evt);
            }
        });
        editProf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("EDIT PROFILE");
        editProf.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-edit-profile-100.png"))); // NOI18N
        editProf.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel4.add(editProf);
        editProf.setBounds(40, 70, 200, 180);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 830, 330));

        jPanel6.setBackground(new java.awt.Color(3, 167, 125));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repsMouseEntered
        reps.setBackground(bodycolor);
    }//GEN-LAST:event_repsMouseEntered

    private void repsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repsMouseExited
        reps.setBackground(headcolor);
    }//GEN-LAST:event_repsMouseExited

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.dispose();
        loginPage lp = new loginPage();
        lp.setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        logOut.setBackground(bodycolor);
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        logOut.setBackground(headcolor);
    }//GEN-LAST:event_logOutMouseExited

    private void editProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfMouseClicked

        //this.dispose();
    }//GEN-LAST:event_editProfMouseClicked

    private void editProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfMouseEntered
        editProf.setBackground(bodycolor);
    }//GEN-LAST:event_editProfMouseEntered

    private void editProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfMouseExited
        editProf.setBackground(headcolor);
    }//GEN-LAST:event_editProfMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel editProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel logOut;
    private javax.swing.JPanel reps;
    // End of variables declaration//GEN-END:variables
}
