/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.db_configuration;
import internalPages.addPage;

import internalPages.searchPage;
import internalPages.updatepage;
import static internalPages.updatepage.tbl_data;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.TableModel;
import static myapp.update.combobox;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maudy
 */
public class managePayroll extends javax.swing.JFrame {

    /**
     * Creates new form viewPage
     */
    public managePayroll() {
        initComponents();
        search_b.setBackground(new Color(100,100,100,100));
    }
    
     updatepage up = new updatepage();
    Color navcolor = new Color(255,0,165);
     Color headcolor = new Color(102,0,51);
      Color bodycolor = new Color(10,177,135);
      
        Color hover = new Color(255,0,165);
    Color defButton = new Color(102,0,51);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void buttonBorderAnimation(JPanel panel){
    panel.setBackground(hover);
    panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    
    }
    
    void buttonDefaultColor(JPanel panel){
    panel.setBackground(defButton);
    panel.setBorder(empty);
    }
  
      
     
      public void fillTable() throws SQLException{
        
    db_configuration dbc = new db_configuration();
    ResultSet rs = dbc.getData("SELECT*FROM tbl_e");
    updatepage u = new updatepage();
       maindesk.add(u).setVisible(true);
    u.tbl_data.setModel(DbUtils.resultSetToTableModel(rs));
   
      }
        public void displayData(){
       
        try{
       
            db_configuration dbc = new db_configuration();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_e");
            tbl_data.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        viewEmp = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        maindesk = new javax.swing.JDesktopPane();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        exitPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        upDate = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        search_b = new javax.swing.JTextField();
        searchIcon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBar.setBackground(new java.awt.Color(255, 0, 165));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(255, 0, 165));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-add-new-24.png"))); // NOI18N
        jLabel13.setText("    ADD EMPLOYEE");
        add.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        navBar.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 60));

        viewEmp.setBackground(new java.awt.Color(255, 0, 165));
        viewEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewEmpMouseExited(evt);
            }
        });
        viewEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-view-24.png"))); // NOI18N
        jLabel15.setText("    VIEW EMPLOYEES");
        viewEmp.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        navBar.add(viewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 60));

        search.setBackground(new java.awt.Color(255, 0, 165));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-mobile-payment-24.png"))); // NOI18N
        jLabel14.setText("    SEARCH PAYROLL");
        search.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        navBar.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/Payroll-Final-Logo (3).png"))); // NOI18N
        navBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(80, 208, 208));
        jLabel11.setText("_____________________");
        navBar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 30));

        jPanel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 690));

        maindesk.setBackground(new java.awt.Color(250, 112, 181));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/dashboard_bg.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        maindesk.add(jLabel9);
        jLabel9.setBounds(-210, -10, 1445, 910);

        jPanel1.add(maindesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 910, 630));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("—");
        minimize.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 30));

        exitPane.setBackground(new java.awt.Color(255, 255, 255));
        exitPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPaneMouseExited(evt);
            }
        });
        exitPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Corbel Light", 1, 20)); // NOI18N
        jLabel7.setText(" x");
        exitPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel2.add(exitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 30));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("←");
        back.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("GENARATOR");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(80, 208, 208));
        jLabel3.setText("PAYROLL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        jPanel3.setBackground(new java.awt.Color(3, 167, 125));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upDate.setBackground(new java.awt.Color(102, 0, 51));
        upDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upDateMouseExited(evt);
            }
        });
        upDate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("UPDATE");
        upDate.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel3.add(upDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, -1));

        delete.setBackground(new java.awt.Color(102, 0, 51));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("DELETE");
        delete.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 90, -1));

        search_b.setForeground(new java.awt.Color(255, 255, 255));
        search_b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(search_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 210, 30));

        searchIcon.setBackground(new java.awt.Color(3, 167, 125));
        searchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchIconMouseExited(evt);
            }
        });
        searchIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-search-client-24.png"))); // NOI18N
        searchIcon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 60, 30));

        jPanel3.add(searchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchPage sp = new searchPage();
        maindesk.add(sp).setVisible(true);
        
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        search.setBackground(bodycolor);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        search.setBackground(navcolor);
    }//GEN-LAST:event_searchMouseExited

    private void viewEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmpMouseEntered
        viewEmp.setBackground(bodycolor);
    }//GEN-LAST:event_viewEmpMouseEntered

    private void viewEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmpMouseExited
        viewEmp.setBackground(navcolor);
    }//GEN-LAST:event_viewEmpMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       addPage ap = new addPage();
       maindesk.add(ap).setVisible(true);
         
    }//GEN-LAST:event_addMouseClicked

    private void viewEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmpMouseClicked
     
        updatepage up = new updatepage();
maindesk.add(up).setVisible(true);
  
          
        try{
            fillTable();
        }catch(SQLException e)
        {
            System.out.println("Error is: "+e);
        }
     
    }//GEN-LAST:event_viewEmpMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new Color(235,233,233));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_minimizeMouseExited

    private void exitPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if(a == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitPaneMouseClicked

    private void exitPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseEntered
        exitPane.setBackground(new Color(204,0,51));
    }//GEN-LAST:event_exitPaneMouseEntered

    private void exitPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseExited
        exitPane.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_exitPaneMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
          
        dashBoard dbp = new dashBoard();
        dbp.show();
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
          back.setBackground(new Color(235,233,233));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
         back.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_backMouseExited

    private void upDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateMouseClicked
      
        int rowindex = tbl_data.getSelectedRow();
        if(rowindex < 0){
             JOptionPane.showMessageDialog(null, "Please select a data first");
        }else{
              update u = new update();
        u.setVisible(true);
            TableModel model = tbl_data.getModel();
            u.emp_id.setText(""+model.getValueAt(rowindex, 0));
            u.emp_name.setText(""+model.getValueAt(rowindex, 1));
              u.emp_bdate.setText(""+model.getValueAt(rowindex, 2));
           
              
              String sex = model.getValueAt(rowindex, 3).toString();
            switch (sex) {
                case "Male":
                    u.male.setSelected(true);
                    break;
                case "Female":
                    u.female.setSelected(true);
                    break;
                default:
                    u.other.setSelected(true);
                    break;
            }
             String cbox = model.getValueAt(rowindex, 4).toString();
               switch (cbox) {
                case "Single":
                    combobox.setSelectedIndex(0);
                    break;
                
                     case "Engaged":
                    combobox.setSelectedIndex(1);
                    break;
                     case "Married":
                    combobox.setSelectedIndex(2);
                    break;
                     default:
                    combobox.setSelectedIndex(3);
                    break;
                
            }
            
            u.emp_department.setText(""+model.getValueAt(rowindex, 5));
                u.emp_job.setText(""+model.getValueAt(rowindex, 6));
                    u.emp_dhired.setText(""+model.getValueAt(rowindex, 7));
                        u.emp_bsal.setText(""+model.getValueAt(rowindex, 8));

        }
    }//GEN-LAST:event_upDateMouseClicked

    private void upDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateMouseEntered
        buttonBorderAnimation(upDate);
    }//GEN-LAST:event_upDateMouseEntered

    private void upDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateMouseExited
        buttonDefaultColor(upDate);
    }//GEN-LAST:event_upDateMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int rowIndex = tbl_data.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select a data first");
        }else{
            TableModel model = tbl_data.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();
            int a=JOptionPane.showConfirmDialog(null,"Are you sure?");
            if(a==JOptionPane.YES_OPTION){
                db_configuration dbc = new db_configuration();
                dbc.deleteData(Integer.parseInt(id));
                displayData();

            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        buttonBorderAnimation(delete);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        buttonDefaultColor(delete);
    }//GEN-LAST:event_deleteMouseExited

    private void searchIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchIconMouseEntered
        searchIcon.setBackground(new Color(25,192,147));
    }//GEN-LAST:event_searchIconMouseEntered

    private void searchIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchIconMouseExited
       searchIcon.setBackground(new Color(3,167,125));
    }//GEN-LAST:event_searchIconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managePayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JPanel back;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel exitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JDesktopPane maindesk;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel search;
    private javax.swing.JPanel searchIcon;
    public static javax.swing.JTextField search_b;
    private javax.swing.JPanel upDate;
    private javax.swing.JPanel viewEmp;
    // End of variables declaration//GEN-END:variables
}
