/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.awt.BasicStroke;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Maudy
 */
public class registerPage extends javax.swing.JFrame {

    /**
     * Creates new form registerPage
     */
    public registerPage() {
        initComponents();
    }
      Color hover = new Color(239,124,239);
    Color defButton = new Color(124,111,207);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void buttonBorderAnimation(JPanel panel){
    panel.setBackground(hover);
    panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    
    }
    
    void buttonDefaultColor(JPanel panel){
    panel.setBackground(defButton);
    panel.setBorder(empty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pword = new javax.swing.JTextField();
        cpass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regsiter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mmzPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exitPane = new javax.swing.JPanel();
        exitPane2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(65, 172, 182));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fname);
        fname.setBounds(450, 80, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 50, 80, 40);

        lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(lname);
        lname.setBounds(450, 150, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 120, 80, 40);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Account");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 0, 240, 44);

        uname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(uname);
        uname.setBounds(450, 220, 240, 30);

        pword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pword);
        pword.setBounds(450, 290, 240, 30);

        cpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(cpass);
        cpass.setBounds(450, 360, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 330, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 260, 80, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 190, 80, 40);

        regsiter.setBackground(new java.awt.Color(124, 111, 207));
        regsiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regsiterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regsiterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regsiterMouseExited(evt);
            }
        });
        regsiter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTER");
        regsiter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(regsiter);
        regsiter.setBounds(520, 420, 110, 30);

        mmzPane.setBackground(new java.awt.Color(204, 0, 153));
        mmzPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmzPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmzPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mmzPaneMouseExited(evt);
            }
        });
        mmzPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("—");
        mmzPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 20, 50));

        jPanel1.add(mmzPane);
        mmzPane.setBounds(690, 0, 40, 30);

        exitPane.setBackground(new java.awt.Color(204, 0, 153));
        exitPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPaneMouseExited(evt);
            }
        });
        exitPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(exitPane);
        exitPane.setBounds(670, 0, 0, 0);

        exitPane2.setBackground(new java.awt.Color(204, 0, 153));
        exitPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPane2MouseExited(evt);
            }
        });
        exitPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Corbel Light", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   x");
        exitPane2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        jPanel1.add(exitPane2);
        exitPane2.setBounds(730, 0, 40, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/regbg.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, -10, 460, 550);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/what-is-payroll.png"))); // NOI18N
        jLabel11.setText("jLabel7");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-280, -20, 650, 510);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regsiterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regsiterMouseExited
        buttonDefaultColor(regsiter);
    }//GEN-LAST:event_regsiterMouseExited

    private void regsiterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regsiterMouseEntered
        buttonBorderAnimation(regsiter);
    }//GEN-LAST:event_regsiterMouseEntered

    private void regsiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regsiterMouseClicked
        JOptionPane.showMessageDialog(null, "Registration complete!");
        loginPage lp = new loginPage();
        lp.setVisible(true);
        this.dispose();
   
    }//GEN-LAST:event_regsiterMouseClicked

    private void mmzPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_mmzPaneMouseClicked

    private void mmzPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseEntered
        mmzPane.setBackground(new Color(255,0,165));
    }//GEN-LAST:event_mmzPaneMouseEntered

    private void mmzPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseExited
        mmzPane.setBackground(new Color(204,0,153));
    }//GEN-LAST:event_mmzPaneMouseExited

    private void exitPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if(a == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitPaneMouseClicked

    private void exitPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseEntered
        exitPane.setBackground(new Color(204,0,51));
    }//GEN-LAST:event_exitPaneMouseEntered

    private void exitPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseExited
        exitPane.setBackground(new Color(204,0,153));
    }//GEN-LAST:event_exitPaneMouseExited

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void exitPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPane2MouseClicked
        loginPage lp = new loginPage();
        lp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_exitPane2MouseClicked

    private void exitPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPane2MouseEntered
        exitPane2.setBackground(new Color(204,0,51));
    }//GEN-LAST:event_exitPane2MouseEntered

    private void exitPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPane2MouseExited
        exitPane2.setBackground(new Color(204,0,153));
    }//GEN-LAST:event_exitPane2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpass;
    private javax.swing.JPanel exitPane;
    private javax.swing.JPanel exitPane2;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel mmzPane;
    private javax.swing.JTextField pword;
    public static javax.swing.JPanel regsiter;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
