/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.db_configuration;
import internalPages.updatepage;
import static internalPages.updatepage.tbl_data;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static myapp.managePayroll.maindesk;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maudy
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
    }
     public void displayData(){
       
        try{
       
             db_configuration dbc = new db_configuration();
    ResultSet rs = dbc.getData("SELECT*FROM tbl_e");
    updatepage u = new updatepage();
       maindesk.add(u).setVisible(true);
    u.tbl_data.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
         try{
       
            db_configuration dbc = new db_configuration();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_e");
            tbl_data.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    }
     public void resetData(){
     emp_id.setText("");
     emp_name.setText("");
     emp_department.setText("");
     emp_bsal.setText("");
     emp_bdate.setText("");
     bgroup.clearSelection();
     emp_job.setText("");
    
     }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bgroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        emp_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emp_bdate = new javax.swing.JTextField();
        other = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emp_department = new javax.swing.JTextField();
        emp_job = new javax.swing.JTextField();
        emp_dhired = new javax.swing.JTextField();
        emp_bsal = new javax.swing.JTextField();
        emp_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 100, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("x");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -3, 10, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 30));

        emp_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Date of Birth");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 30));

        emp_bdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_bdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emp_bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, 30));

        other.setBackground(new java.awt.Color(0, 204, 153));
        bgroup.add(other);
        other.setText("Other");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), other, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });
        jPanel1.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        male.setBackground(new java.awt.Color(0, 204, 153));
        bgroup.add(male);
        male.setText("Male");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, male, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), male, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Sex");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 50));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Engaged", "Married", "Widow" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 270, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Basic Salary");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date Hired");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Job Title");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Department");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 160, 30));

        emp_department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emp_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_departmentActionPerformed(evt);
            }
        });
        jPanel1.add(emp_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 270, 30));

        emp_job.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_job.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emp_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_jobActionPerformed(evt);
            }
        });
        jPanel1.add(emp_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 270, 30));

        emp_dhired.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_dhired.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emp_dhired, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 270, 30));

        emp_bsal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_bsal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emp_bsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, 30));

        emp_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 62, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        female.setBackground(new java.awt.Color(0, 204, 153));
        bgroup.add(female);
        female.setText("Female");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), female, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        db_configuration dbc = new db_configuration();
        int num = 0;
        num = dbc.updateData("UPDATE tbl_e "
                + "SET e_name = '"+emp_name.getText()+"', "
                + "e_bdate='"+emp_bdate.getText()+"', "
                + "e_sex ='"+bgroup.getSelection().getActionCommand()+"', "
                + "e_status ='"+combobox.getSelectedItem().toString()+"',"
                + "e_dep='"+emp_department.getText()+"'"
                + ",e_job ='"+emp_job.getText()+"',"
                + "e_dhired ='"+emp_dhired.getText()+"',"
                + "e_bsal='"+emp_bsal.getText()+"'  "
                + "WHERE e_id = '"+emp_id.getText()+"'");
       
      
             resetData();
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayData();    
          this.dispose();
          
          
          
          
        
    
    }//GEN-LAST:event_updateActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
      
    }//GEN-LAST:event_otherActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
     
    }//GEN-LAST:event_maleActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void emp_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_departmentActionPerformed

    private void emp_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_jobActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup bgroup;
    public static javax.swing.JComboBox<String> combobox;
    public static javax.swing.JTextField emp_bdate;
    public static javax.swing.JTextField emp_bsal;
    public static javax.swing.JTextField emp_department;
    public static javax.swing.JTextField emp_dhired;
    public static javax.swing.JTextField emp_id;
    public static javax.swing.JTextField emp_job;
    public static javax.swing.JTextField emp_name;
    public static javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton male;
    public static javax.swing.JRadioButton other;
    private javax.swing.JButton update;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
